---
language: ruby
notifications:
  email:
    - mike@blowmage.com
rvm:
  - 2.6.3
  - 2.6.0
  - 2.5.5
  - 2.5.0
  - 2.4.6
  - 2.4.0
  - 2.3.8
  - 2.3.0
gemfile:
  - gemfiles/rails-5.2.gemfile
  - gemfiles/rails-5.1.gemfile
  - gemfiles/rails-5.0.gemfile
