---
before_install:
  - gem update --system
  - gem --version
language: ruby
notifications:
  email:
    - mike@blowmage.com
rvm:
  - 2.6.3
  - 2.6.0
  - 2.5.5
  - 2.5.0
  - ruby-head
gemfile:
  - gemfiles/rails-6.0.0.gemfile
