---
before_install:
  - gem update --system
  - gem --version
language: ruby
notifications:
  email:
    - mike@blowmage.com
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
env:
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=4.2"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c3806b220bb40c23430e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   false   # default: false
