version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build_2.7.2:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Build CI
          command: bundle exec rake ci
  build_2.6.6:
    docker:
      - image: circleci/ruby:2.6.6
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Build CI
          command: bundle exec rake ci
  build_2.5.8:
    docker:
      - image: circleci/ruby:2.5.8
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Build CI
          command: bundle exec rake ci

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_2.7.2
      - build_2.6.6
      - build_2.5.8
